version: "3"

services:
  api:
    build: .
    ports:
      - "5000:5000"
<<<<<<< HEAD

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

    volumes:
      - app_data:/app/data

volumes:
  app_data:
=======
>>>>>>> b006571910c1276587d0dc4eec25479aa08acbd9
